name: release

on:
  release:
    types:
      - created

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v1.2.1
      with:
        version: v1.29      
    - name: Generate build files
      uses: thatisuday/go-cross-build@v1
      with:
        platforms: 'linux/amd64, windows/amd64'
        name: 'program'
        compress: 'true'
        dest: 'dist'